version: ~> 1.0

# If the language is set to C or C++, Travis defines and exports CC
# and CXX *after* we have defined our environment variables via 'env'.
language: minimal

# Run in two steps:
# 1. Build the tarball
#    On a modern distro, with all the needed dependencies, including the whole git history.
# 2. Check it on various environments.
#    Less dependencies, and little git content (we would like to have none, but it's not
#    an option on Travis).
stages:
  - dist
  - check

# The 'check' jobs do not need the repo at all, only the 'dist'
# does.  Let's save time, bandwith, energy, and polar bears.
git:
  clone: false

# matrix.include and jobs.include are aliases
# (https://docs.travis-ci.com/user/conditional-builds-stages-jobs/).
jobs:
  include:
    - stage: dist
      name: "Make dist"
      git:
        clone: true
      dist: bionic
      script:
        - sudo apt-get install -qq autoconf automake autopoint flex gettext graphviz help2man m4 texinfo
        - autoconf --version
        - automake --version
        - autopoint --version
        - dot -V
        - gettext --version
        - help2man --version
        - makeinfo --version
        - m4 --version

        # Travis makes a shallow clone, but we need it in full to build the ChangeLog and apply the fixes in git-log-fix.
        - git fetch --unshallow || true
        - git submodule update --init --recursive

        - ./bootstrap
        - ./configure --enable-gcc-warnings || { cat config.log && false; }
        - make -j2
        - make -j2 dist
        # Can help understanding why we get "dirty" tarballs.
        - git status
        - dist=$(echo bison*.xz)

        # Unfortunately we cannot deterministically know the name of the tarball without the full
        # git history (because git describe --abbrev=4 may use more than 4 characters if there are
        # conflicts).
        #
        # So for the sake of the 'check' jobs (that don't even have the repo at all), also expose this
        # tarball on a name that only depends on the Travis build number.
        #
        # Without -b -, exit status is always 0.
        #
        # If we rerun a job that was already uploaded, 'ln -s' will fail: remove beforehand.
        - sftp -b - bison@sftp.lrde.epita.fr <<< "put $dist"$'\n'"-rm bison-$TRAVIS_BUILD_NUMBER.tar.xz"$'\n'"ln -s $dist bison-$TRAVIS_BUILD_NUMBER.tar.xz"

    ## ------- ##
    ## First.  ##
    ## ------- ##

    # Start with three completely different environments, to get
    # errors asap.


## From https://docs.gitlab.com/ce/ci/ssh_keys/#ssh-keys-when-using-the-docker-executor.
## Applies to Travis too.  Applied to all the 'script's (of all the jobs).
before_script:
  - 'which ssh-agent || ( sudo apt-get install openssh-client -y )'
  - eval "$(ssh-agent -s)"
  # $SSH_PRIVATE_KEY is multiline.  Use $'...' to register its value: $'-----BEGIN OPENSSH PRIVATE KEY-----\nXXXXX...\n...==\n-----END OPENSSH PRIVATE KEY-----'.
  - echo "$SSH_PRIVATE_KEY" >/tmp/key.id_rsa
  - chmod 600 /tmp/key.id_rsa
  - ssh-add /tmp/key.id_rsa </dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo '|1|bpc51UGxoDZjCPiwRlCStW32trI=|rfh6mLoLZv/vAvOVrpZXI1hTLxg= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIR+ckMoJTNXHvAQLHWSfrRnrNJGW2ZR6kr5pBVDGCkz1v1RcQ5rleq0NAt9kS3v4hgnuLiEVnK7KDRzcEH3ikc=' >>~/.ssh/known_hosts
  - chmod 600 ~/.ssh/known_hosts

# Applies only to the jobs that don't have a 'script', i.e., applies to all the 'check' jobs, but not the 'dist' one.
script:
  # Beware not too leak $SSH_PRIVATE_KEY.
  # - env
  - sudo apt-get install -qq doxygen flex m4
  # Install and activate dmd.
  - mkdir -p ~/dlang && wget https://dlang.org/install.sh -O ~/dlang/install.sh
  - source $(source ~/dlang/install.sh dmd -a)

  - $CC --version
  - $CXX --version
  - dmd --version
  - doxygen --version
  - flex --version
  - ld --version
  - m4 --version

  - if [[ -f ~/.bashrc ]]; then source ~/.bashrc; fi
  # Unset this variable, otherwise, Java programs' stderr is cluttered
  # with `Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m`, which makes
  # the test suite fail.
  - unset _JAVA_OPTIONS

  # Fail fast from now on.
  - set -e
  - sftp bison@sftp.lrde.epita.fr:bison-$TRAVIS_BUILD_NUMBER.tar.xz
  - tar xf bison-$TRAVIS_BUILD_NUMBER.tar.xz
  - dir=$(tar tf bison-$TRAVIS_BUILD_NUMBER.tar.xz | sed 1q)
  - cd $dir
  - mkdir _build
  - cd _build
  - ../configure --enable-gcc-warnings CC="$CC" CXX="$CXX" $CONFIGUREFLAGS || { cat config.log && false; }
  - make -j2 $MAKE_ARGS
  - if test ${PART-1} = 1; then make check                  VERBOSE=1 TESTSUITEFLAGS=-j2 || { cat test-suite.log && cat tests/testsuite.log && false; }; fi
  - if test ${PART-2} = 2; then make maintainer-check-posix VERBOSE=1 TESTSUITEFLAGS=-j2 || { cat tests/testsuite.log && false; }; fi
  - if test ${PART-2} = 2; then make maintainer-check-g++   VERBOSE=1 TESTSUITEFLAGS=-j2 || { cat tests/testsuite.log && false; }; fi
