# Travis defines and exports CC and CXX *after* we have defined our
# environment variables via 'env'.  So, do not use 'env' to define
# them.  Instead, put their definitions in MATRIX_EVAL, which we eval
# after the definitions from Travis.

language: cpp

env:
  global:
    # ICC serial number.
    secure: ED3w6rzxuE6tVu3oyxha2MoGMRzRQCtinvr9uor1gw9TGKB80esTLx4KyX0xHemUdyQVarFDDQfVS5rf7jSDY8XiWIR6O+2Af9/30gb+8eyngyvACu7E28n+1XHmYWIEHsbvB9mic6C60FBj5sPcDnFWZeyttGL0WooSjYHiw1Egafwqbeu1mD3Aet9OI9VaLQvy0KcWAdVrYWSI9UWLvLM+xPVUjPFko4oS+dTlETzVnmn6JFbZX1OKONtfcvdoDRFBzs3iHm5dQUt/Fz+y/DtKSuvF3zvePHSgF6c8URbEPPjBdh87gkovSLyy+83fVeh4WMkF8b+dGZmikQv6kRsjKJdbQrS8tiMhZlORC5Gfmn4HXNgmapL+paUweakH7UZQHm6d5SZoBgCHNazfqMrywbZsZkGvZTDQIVG1Be7Lhh2BDFbPhPZNDvI9XYiqZP0QSb0BVfeO+AUSRcUPM7TvarxB74jYdfpTBu7sqJP6dSwhcDTEUhHmuLGjzsNm3uTZe8SUw/TGGx5uPTXNsCjJq6ClIOAIYXZTXLbBmIL/NBWCy0MUpD+9zsiknU7vzzq1RfgCCExhvYgosTjBLcX1kKI+eRSU5M44e+xCg4xx0m9WfafbKbhA20FfnWxCFIkZeVpkOOsexJ9zfe0SflVLxkd7vmci5SCBixLVbN0=

cache:
  directories:
    - '$HOME/.sonar/cache'

matrix:
  include:

    # See https://github.com/SonarSource/sq-com_example_c-sqscanner-travis.
    - name: "Sonar"
      os: linux
      addons:
        sonarcloud:
          organization: "akimd-github"
          token:
            secure: "b1ZBfMK80J6rW1mz706uDcFHohLJGBF6+3H+smL5VFsWwbIMbibowWWtWBAE15vDpawGB3fTPPJgyJ+Z8vO8hbbMXXCu7BQzGxOFivkJMCA3aPDQ3LLyX5ovBqa4LHjNSFYNeOvoOJrvAekW5matm4jh3WRRMXdKLYks7T2MCsDkFsdbaUS6cFwDBMa3zctjgrslb2HFBuY3A7WHsvKRyYaDX+ZWGeSSteMBOlm2vc1q7XJbKIiq0gcvjjQIgaj9c3pMz4/Qunqpcm+2NafS423WSw2qPpoVfj0KHfZseh57uokmHJ0ghPVcOIYG1vdmJDXmLcDG0MvRvMDFeuwmXklnfutlJ4D2RxfimQFA+J9X7WJMjZX7zM2ZMsdTVnExOOcGJMY6EeXNGnlE8fKkHORoSWbVGqy6nWbkoUmgcSni25+GX1ADIHOjfPJQMXeEK+PIiJ5V9hUUUrevf1UbL+aL6FWSy45H4wzM+wW62d+gF25xwb1g3PWX6sh7YqiKYJtH/vaDfUvHtYIg1f3b0cBwcecOlN6R92NAC+iS0+smX8BEGZXE+dXov5Je0im/f1XRDROv6wIYFGoyC/NC/LZ0+I5/GxoNgYE+bcX4EpZ9hry46Ex0CMwxcjW+DQwjimnJpAhsRbyGp3aX4NFJdzPJGQP9NMoWmgTZHQ/W+k8="
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && SONAR=true"


before_install:
  - eval "$MATRIX_EVAL"
  - env
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf automake autopoint doxygen flex gettext graphviz help2man m4 texinfo
  - if [[ $CC == "icc" ]]; then build-aux/install-icc.sh; fi
  - if [[ -f ~/.bashrc ]]; then source ~/.bashrc; fi
  - autoconf --version
  - automake --version
  - autopoint --version
  - $CC --version
  - $CXX --version
  - doxygen --version
  - flex --version
  - gettext --version
  - dot -V
  - help2man --version
  - m4 --version
  - makeinfo --version

script:
  - git show
  - git tag -l
  # For some reasons, sometimes the checkout does not have any tags,
  # so `git describe` fails, so bootstrap fails.
  - git describe || git tag v3.0 -m "Fake version 3.0."
  - git describe
  - ./bootstrap
  - if [[ -f ~/.bashrc ]]; then source ~/.bashrc; fi
  - ./configure --enable-gcc-warnings CC="$CC" CXX="$CXX" $CONFIGUREFLAGS || { cat config.log && false; }
  - ${SONAR+build-wrapper-linux-x86-64 --out-dir bw-outputs} make -j2 $MAKE_ARGS
  - make check                  VERBOSE=1 TESTSUITEFLAGS=-j2 || { cat tests/testsuite.log && false; }
  - make maintainer-check-posix VERBOSE=1 TESTSUITEFLAGS=-j2 || { cat tests/testsuite.log && false; }
  - make maintainer-check-g++   VERBOSE=1 TESTSUITEFLAGS=-j2 || { cat tests/testsuite.log && false; }
  - ${SONAR+sonar-scanner}


after_script:
  - if [[ $CC == "icc" ]]; then uninstall_intel_software; fi
